apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-webapp
  labels:
    app: helm-webapp
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: helm-webapp
  template:
    metadata:
      labels:
        app: helm-webapp
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: helm-webapp-nginx-html